### PR TITLE
Add `gcsfs` to requirements.txt

### PR DESCRIPTION
**Pull request by sjfleming**
@jamesemery , should there be a specific version required?

### CODE REVIEW

**Comment by sjfleming** [comment]
Closes #217

**Comment by jamesemery** [comment]
@sjfleming heh looks like this IS my fault... I am not an expert in python package management so I can't say if it should matter what version we peg it to but if we do we should make sure to update it in both this place and in dev-requirements.txt.

**Comment by SHuang-Broad** [comment]
Should there be a test for `requirements.txt`?
E.g. `pip check` in the test infrastructure?

**Comment by sjfleming** [comment]
@jamesemery oh, I see you already have it included in `dev-requirements.txt`.

To be honest, I'm not sure I see where `dev-requirements.txt` is ever used?  I must be missing the reference to it from somewhere

**Comment by sjfleming** [comment]
@SHuang-Broad I didn't know about `pip check`.   Sounds interesting

**Comment by sjfleming** [comment]
I'll wait for @bshifaw 's input before I merge

**Comment by bshifaw** [comment]
Yes! thanks, good to merge

**Review by bshifaw — APPROVED** [review]

**Pull request merged**
