### PR TITLE
Add ability to load a cromshell plugin on startup.

### PR DESCRIPTION
**Pull request by lbergelson**
This allows users to easily customize their cromshell.

@jonn-smith What do you think about this idea?  I wanted an easy way to change the default colors without having to add a whole bunch of configuration code.

### CODE REVIEW

**Comment by jonn-smith** [comment]
I guess that's fine.  I have no real objection, other than the user possibly putting something bad in that file that then comes back to haunt them.

**Comment by lbergelson** [comment]
Do you think there's a better way that prevents people from shooting themselves in the foot?

**Comment by lbergelson** [comment]
I'm not sure how to encapsulate it like that.  I.e. prevent setting the server through the plugin.  This is just giving the user the ability to override whatever they want which definitely could be used for stupid.

**Comment by jonn-smith** [comment]
Maybe a shell script isn't the right approach, then.  What about a JSON file (or similar)?

**Comment by lbergelson** [comment]
Closing this.  We're addressing plugins as part of cromshell 2.0.

**Pull request closed without merging**
